### ISSUE TITLE
Suggestion: ignore locked skills

### ISSUE THREAD

**Issue by DenDrummer** [KumaV1/Skilling-limited-Combat-in-Melvor#2]
The only real problem I have with this mod is that due to the Herbalism skill, you're stuck at level 1 combat, and thus level 3 non-combat.

Garum Herbs, which you need for the only thing you can craft at lvl 1 Herbalism, can't be acquired at level 3 non-combat skills.
This isn't a problem in Standard or Hardcore mode, but it is in Adventure mode (or the Random Adventure mode from another mod).
Seeing as Herbalism is a vanilla, core-game, non-combat skill, this causes a bit of a problem due to non-combat skills being limited by combat level.

To fix this, I'd suggest to only look at the unlocked non-combat skills.
From the description, this is also what I assumed it was going to do before I installed it.

**Comment by KumaV1** [comment]
**EDIT**: I just realized that Adventure-mode itself limits your skilling levels. Yeah, good luck getting the money for all skills while being locked to level 3 everywhere (lol)... So yeah, there probably has to be some leniency to that restriction in combination with Adventure mode or locked skills in general. Right now, I would probably go with the mod setting mentioned in the last paragraph, feel free to let me know what you think of that idea. And again, thanks for the feedback!

---

Hey, thank you for the feedback.

First I want to clarify something, in case there is a misunderstanding (based on your first sentence). This mod is **not** meant to block your non-combat skill levels in any way. So, if you are able to unlock Farming (for planting seeds) or Township (for herb packages), then by training those up first, you should still be able to aquire herbs to train Herblore, even if there are no low-level combat encounters that can provide you with herbs directly (the Lvl6 farmer has enough seeds to get you started on training Farming). With that in mind, this mod would then just cause you to prioritize those skills (or hope you don't get unlucky in the Randomized Adventure Mod), so I don't see an issue with this mod "blocking your progress" so to speak.

---

As for locked skills in general, my thought progress was that you could basically "cheese" yourself resources through combat, as long as you start with combat before starting to unlock skills. I'm not sure, if strategically taking advantage of that would go too much against the nature of the mod, though I can definitely see how this mod sort of "hart-locks" you out of any relevant combat for quite some time during Adventure mode, as it will take a while to unlock all skills. 

With that being said, I could definitely create a setting which let's you choose whether or not locked skills block you from gaining combat xp. I would probably also adjust the behaviour of you training combat with a low level skill (as it technically resets your xp to the lowest skill's level right now, as warned in the mod description), so it gives an xp punishment instead (e.g. reducing your xp by flat 1000xp or 1% of your current xp anytime you would gain xp, depending on which value is higher), to still discourage you from doing combat at all, until you have gotten the newly aquired skill up-to-par with your other skills.

**Comment by DenDrummer** [comment]
Yeah, after having double checked the wiki, the only source for garum herbs with lvl 1 combat skills and lvl 3 non-combat skills would be the druid in the runic ruins, which is almost impossible that early in the game, locking you out of the herbalism skill in adventure.

So I was also thinking something along the lines of the setting you described. It could be an option of

Reset to: 
• lowest skill
• lowest unlocked skill

Small footnote: I personally haven't seen skills being locked outside of adventure mode or tutorial island*, so I don't think it'd affect non-adventure playthroughs if it became the new default.
_*(haven't played hardcore though, not my cup of tea)_

The xp punishment instead of flat out reset is certainly a neat idea, but honestly? I wouldn't mind keeping the old reset as long as I can ignore unlocking herbalism to still be able to progress to at least combat level 5, at which point I'd be able to at least use the farm for garum herbs, as garum seeds aren't a problem at all. So with ignoring locked non-combat skills, that should become possible.

I will admit I have no experience with the Melvor Idle modding API, so idk how easy/difficult filtering out the (non-)locked skills would be though.

ps: Sorry for the unorganized mess of thoughts, but I hope I got my ideas across well enough :)

EDIT: though I will say, if it's possible to show a warning popup on unlocking the first skill making the reset clear, that might also be a good idea. (I can imagine a good portion of users not reading the full description :P )

**Comment by KumaV1** [comment]
Filtering out unlocked skills is actually **very** easy. I will probably go with the "locked or non-locked skill" mod setting for the implementation. (presumably some time today/tomorrow, depending on timezone)
![grafik](https://github.com/KumaV1/Skilling-limited-Combat-in-Melvor/assets/146348901/0d9cf31a-0ff7-4754-be8b-342f28d54c71)

Also, as a note to myself, I checked the behaviour for the warn message to appear, and its current behaviour is bad and slightly bugged I think, probably not helping against xp reset as much as it's supposed to. (also relocate it to below the area selections, so it's more "in your face")
![grafik](https://github.com/KumaV1/Skilling-limited-Combat-in-Melvor/assets/146348901/10b62f81-cb41-4cb4-bd41-39a0434672cf)

**Comment by DenDrummer** [comment]
just noticed that Bulbasaur, (pokémon mod) does drop Garum Herb too, but uhm...
That's not gonna be a feasible option either xD (see screenshot)

![image](https://github.com/KumaV1/Skilling-limited-Combat-in-Melvor/assets/17620245/9cb0b57d-c66e-434f-8c9b-8d71ffe476f0)

**Comment by KumaV1** [comment]
Well, another source of Garum Herbs won't help much, if you can't progress much through Herblore anyway^^ (with Adventure mode and the mod limiting each other)

The implementation is pretty much done, so I'll be able to push an update once I wake up tomorrow.

Also, I reckon the warning should be a bit more intuitive and reliable. Right now, the display will be evaluated in the following situations, which should cover everyting. Granted, it will basically appear permanently at the beginning, because Hitpoints is also a combat skill, so while it's not reset below level 10, it will cause the warning to appear until you are allowed to go above level 10.
* On loading the character
* If the reset of xp occurs
* If you unlock any skill
* If you level up any skill
* If you change the setting
![grafik](https://github.com/KumaV1/Skilling-limited-Combat-in-Melvor/assets/146348901/e16e26f9-15fb-4e98-8e67-7efaa203ec4b)
![grafik](https://github.com/KumaV1/Skilling-limited-Combat-in-Melvor/assets/146348901/0ec4a92e-add8-45fb-82ee-2fc6d0e7b9ec)
